#ifndef _PIPELINE_CMD_H
#define _PIPELINE_CMD_H

#define GPU_PIPELINE_CMD_MIN        0xFFFFFF00

#define GPU_PIPELINE_POLY_VERTEX    0xFFFFFF00
#define GPU_PIPELINE_FRAME_END      0xFFFFFF01
#define GPU_PIPELINE_FRAGMENT       0xFFFFFF02

#endif
