.PHONY: cxxstages

CXXSTAGES_DIR = stages/c++/

cxxstages:
	$(MAKE) -C $(CXXSTAGES_DIR)/test_vertices
	$(MAKE) -C $(CXXSTAGES_DIR)/vertex_transform
	$(MAKE) -C $(CXXSTAGES_DIR)/rasterizer
	$(MAKE) -C $(CXXSTAGES_DIR)/fragment_ops
